env:
  browser: true
  es6: true
extends: 
  - standard
  - plugin:react/recommended
  - plugin:jest/recommended
rules:
  semi: 0
  camelcase:
    - error
    - allow: ["UNSAFE_componentDidMount", "UNSAFE_componentWillMount", "UNSAFE_componentWillUnmount"]
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - jest
