language: node_js
node_js:
  - 11.6.0
cache: npm

script: 
  - npm test
  - npm run build
  - npm run dist

deploy:
  provider: releases
  skip-cleanup: true
  file: dist/dynosign*.AppImage
  github-token: $GITHUB_TOKEN
  draft: true