language: node_js
node_js:
  - 11.6.0
cache: npm

matrix:
  include:
    - os: linux
      env: DEPLOY_FILE=dist/dynosign*.AppImage
    - os: windows
      env: DEPLOY_FILE=dist/dynosign Setup*.exe

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rvm install 2.6.0 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rvm use 2.6.0 ; fi
  - gem update --system && gem install bundler -v 2.0.1 --no-document
  #if gems are missing this script will get the missing gems.
  - mkdir -p gh-pages/assets/images && cp {output*.gif,javascripts/LeftBar/*.svg,screen.png,templogo.png} gh-pages/assets/images
  - npm ci

script: 
  - npm test
  - npm run build
  - npm run dist
  - mkdir -p gh-pages/docs && npm run doc
  - cd gh-pages && bundle check || bundle install && jekyll build 

notifications:
  email: false

jobs:
  allow_failures:
    - os: windows

deploy:
  - provider: releases
    skip-cleanup: true
    file: $DEPLOY_FILE
    github-token: $GITHUB_TOKEN
    api_key: $GITHUB_TOKEN
    on:
      tags: true

  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    api_key: $GITHUB_TOKEN
    local_dir: gh-pages/_site
    on:
      branch: master