language: node_js
node_js:
  - 11.6.0
cache: npm

before_install:
  - rvm install 2.6.0
  - rvm use 2.6.0
  - gem update --system && gem install bundler -v 2.0.1 --no-document
  #if gems are missing this script will get the missing gems.
  - cp output*.gif gh-pages/assets/images && cp javascripts/LeftBar/*.svg gh-pages/assets/images
  - cd gh-pages && bundle check || bundle install && jekyll build 
  - npm ci

script: 
  - npm test
  - npm run build
  - npm run dist
  - mkdir -p gh-pages/docs && npm run doc

notifications:
  email: false

deploy:
  - provider: releases
    skip-cleanup: true
    file: dist/dynosign*.AppImage
    github-token: $GITHUB_TOKEN
    api_key: $GITHUB_TOKEN
    on:
      tags: true

  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    api_key: $GITHUB_TOKEN
    local_dir: gh-pages/_site
    on:
      branch: master